### ISSUE TITLE
Does not compile with ghc 8.4.3

### ISSUE THREAD

**Issue by dsh** [adinapoli/mandrill#47]
```
    [ 3 of 13] Compiling Network.API.Mandrill.Types ( src/Network/API/Mandrill/Types.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Network/API/Mandrill/Types.o )

    /tmp/stack2029/mandrill-0.5.3.3/src/Network/API/Mandrill/Types.hs:161:10: error:
        • No instance for (Semigroup MandrillHtml)
            arising from the superclasses of an instance declaration
        • In the instance declaration for ‘Monoid MandrillHtml’
        |
    161 | instance Monoid MandrillHtml where
        |          ^^^^^^^^^^^^^^^^^^^
```

**Comment by dsh** [comment]
Confirmed working. Thank you!
